### ISSUE TITLE
Native tracer templates not working after geth update

### ISSUE THREAD

**Issue by bhargavtheertham-cb** [stackup-wallet/erc-4337-execution-clients#45]
Hi Team,
The templates that we have available for native tracers is no longer working after update to v1.101408.0.
It looks like this [PR](https://github.com/ethereum-optimism/op-geth/commit/064f37d6f67a012eea0bf8d410346fb1684004b4) introduced changes the tracer.Trace interface which requires changes to the go templates. Please let us know if those changes would be made to the templates. Thanks

```
Here we add a Go API for running tracing plugins within the main block import process. 

As an advanced user of geth, you can now create a Go file in eth/tracers/live/, and within
that file register your custom tracer implementation. Then recompile geth and select your tracer
on the command line. Hooks defined in the tracer will run whenever a block is processed.

The hook system is defined in package core/tracing. It uses a struct with callbacks, instead of 
requiring an interface, for several reasons:

- We plan to keep this API stable long-term. The core/tracing hook API does not depend on
  on deep geth internals.
- There are a lot of hooks, and tracers will only need some of them. Using a struct allows you
   to implement only the hooks you want to actually use.

All existing tracers in eth/tracers/native have been rewritten to use the new hook system.

This change breaks compatibility with the vm.EVMLogger interface that we used to have.
If you are a user of vm.EVMLogger, please migrate to core/tracing, and sorry for breaking
your stuff. But we just couldn't have both the old and new tracing APIs coexist in the EVM.
```

**Comment by bhargavtheertham-cb** [comment]
@hazim-j it looks like you have pushed the updated code last night. We will use the new go templates for bundler and executor

**Comment by hazim-j** [comment]
Hi @bhargavtheertham-cb, yup! These two files should be compatible with the new geth native tracer interfaces:
- tracers/bundler_collector_next.go.template
- tracers/bundler_executor_next.go.template

Will close this for now but LMK if there are any issues.
